# Theme colors — generated by `dot theme render`
# Do not edit manually — changes will be overwritten

default_border pixel 1
default_floating_border pixel 1
smart_borders on

client.focused {{ accent_2 }} {{ accent_2 }} {{ background }} {{ accent_2 }} {{ accent_2 }}
client.focused_inactive {{ border }} {{ border }} {{ foreground }} {{ border }} {{ border }}
client.unfocused {{ border }} {{ background }} {{ muted_foreground }} {{ border }} {{ border }}
client.urgent {{ urgent }} {{ urgent }} {{ selection_foreground }} {{ urgent }} {{ urgent }}
client.placeholder {{ border }} {{ muted_background }} {{ muted_foreground }} {{ border }} {{ border }}
client.background {{ background }}
