# NTS-authenticated time servers
server oregon.time.system76.com iburst nts
server virginia.time.system76.com iburst nts
server ohio.time.system76.com iburst nts

# Fedora pool
pool 2.fedora.pool.ntp.org iburst

# Use NTP servers from DHCP
sourcedir /run/chrony-dhcp

# Record the rate at which the system clock gains/losses time
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC)
rtcsync

# Save NTS keys and cookies
ntsdumpdir /var/lib/chrony

# Insert/delete leap seconds by slewing instead of stepping
leapseclist /usr/share/zoneinfo/leap-seconds.list

# Specify directory for log files
logdir /var/log/chrony
