accent = "#4385BE"
cursor = "#CECDC3"
foreground = "#CECDC3"
background = "#100F0F"
selection_foreground = "#100F0F"
selection_background = "#CECDC3"

color0 = "#1C1B1A"
color1 = "#D14D41"
color2 = "#879A39"
color3 = "#D0A215"
color4 = "#4385BE"
color5 = "#CE5D97"
color6 = "#3AA99F"
color7 = "#CECDC3"
color8 = "#575653"
color9 = "#E8705F"
color10 = "#A0AF54"
color11 = "#EBC06D"
color12 = "#61A0D7"
color13 = "#E49FC0"
color14 = "#58C2B8"
color15 = "#FFFCF0"
