# Firefox Extensions Configuration
# Format: name:extension_id:addon_slug

1password:{d634138d-c276-4fc8-924b-40a0ea21d284}:1password-x-password-manager
ublock:uBlock0@raymondhill.net:ublock-origin
kagi:search@kagi.com:kagi-search-for-firefox
harper:harper@writewithharper.com:private-grammar-checker-harper
tabsession:Tab-Session-Manager@sienori:tab-session-manager
obsidian:clipper@obsidian.md:web-clipper-obsidian
untrap:{2662ff67-b302-4363-95f3-b050218bd72c}:untrap-for-youtube
eagle:{228a49ed-af0c-452c-bc77-630f99cb0470}:eagle-for-firefox
frankerfacez:frankerfacez@frankerfacez.com:frankerfacez
